### ISSUE TITLE
命名について

### ISSUE THREAD

**Issue by h-metsugi** [shunk0113/InternshipProject_2021#10]
https://github.com/shunk0113/InternshipProject_2021/pull/3/files#diff-59278d67fd047953131b11c0d5b26bae5aeae7ea20b5d27aeacefd86839c2a4c

今回の制作で無理に修正する必要はないですが、  
フィールド名等については一貫性のある命名を推奨します。  
一貫性が崩れると思わぬミスや検索の阻害など後々悪影響が出る可能性があります。

**Comment by h-metsugi** [comment]
@Nakaseeee 
Assignees変更できないのでとりあえずメンションつけておきます

**Comment by Nakaseeee** [comment]
@h-metsugi 
ご指摘ありがとうございます。
実は、自分の中では規則的に命名しているつもりなのですが、いわゆるスネークケースかキャメルケースか、どちらか一方に統一しろ、という解釈でよろしいでしょうか？

**Comment by h-metsugi** [comment]
指摘の意図としてはそうなりますね。  
ただ、ご自分でその辺りの区別をつけて命名しているのであれば今回は大丈夫です。   
サンプルが少なくて判別できなかったのもありますので。  
コーディング規約などが存在すればまた話は変わってきますが…
