### ISSUE TITLE
Transform取得処理の冗長性ついて

### ISSUE THREAD

**Issue by h-metsugi** [shunk0113/InternshipProject_2021#9]
- https://github.com/shunk0113/InternshipProject_2021/pull/3/files#diff-59278d67fd047953131b11c0d5b26bae5aeae7ea20b5d27aeacefd86839c2a4cR31
- https://github.com/shunk0113/InternshipProject_2021/pull/3/files#diff-59278d67fd047953131b11c0d5b26bae5aeae7ea20b5d27aeacefd86839c2a4cR114

GaomeObjectのTransformをGetComponetで取得すると冗長なので  
プロパティにアクセスする方がよいかと思われます。

**Comment by h-metsugi** [comment]
@Nakaseeee

**Comment by Nakaseeee** [comment]
@h-metsugi 
確かにその通りですね。プロパティを失念していました。
コードを修正します。
